### ISSUE TITLE
React TODO List

### ISSUE THREAD

**Issue by havietduc91** [havietduc91/reactjs-2021#1]
- [ ] React Boilerblate https://medium.com/geekculture/react-js-architecture-features-folder-structure-design-pattern-70b7b9103f22
- [ ] Redux
- [ ] React Bootstrap, Material UI
- [ ] React Router 
- [ ] Redux Form, React Form, 
- [ ] Form validate
- [ ] Axios
- [ ] GraphQL
- [ ] Use State
- [ ] Life cycle
- [ ] Eslint
- [ ] Sonarqube
- [ ] Coding convention
- [ ] SASS
- [ ] Unit test cypress
- [ ] Build env prod, staging, test, dev
- [ ] Add third party
- [ ] Dump & container
- [ ] Performance
- [ ] React Dev Tool
- [ ] Best Practice
- [ ] Source map exploxer
